### ISSUE TITLE
Age of Mythology CopyRects issue

### ISSUE THREAD

**Issue by WinterSnowfall** [AlpyneDreams/d8vk#38]
![AOM](https://user-images.githubusercontent.com/6306593/197393500-a9cb7b3f-2aa6-43ed-a0c5-4a57254f15c7.png)

The game starts and the main menu background music can be heard, but nothing is visible, except for some occasional water waves in certain situations, and the game cursor.

Unfortunately apitrace makes the game crash, but the debug logs print this message repeatedly:

`debug: CopyRects: Hit unhandled case from src pool 2 to dst pool 1`

### Software information
Age of Mythology + The Titans expansion (retail d3d8 version)

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.76
- Wine version: 7.19 Staging
- DXVK version: 7cd4c8b

### Apitrace file(s)
None, unfortunately :(

### Log files
- d3d8.log: [aomx_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/9846607/aomx_d3d8.log)
- d3d9.log: [aomx_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/9846608/aomx_d3d9.log)

**Comment by AlpyneDreams** [comment]
I've updated CopyRects. Try with the latest commit and let me know if it works.

**Comment by WinterSnowfall** [comment]
![AOM](https://user-images.githubusercontent.com/6306593/197458477-bb4fe422-bed5-4653-b899-68be2261b362.png)

The debug messages are indeed gone, and there's some progress... but sadly looks like only the menu text was fixed.

Unfortunately can't give you more than a [d3d9 trace captured with d3d8to9](https://drive.google.com/file/d/1EWpzV6cAzF9c0g9MkQ-HA-ld9lXHm4f1/view?usp=sharing), if that helps in any way. Tracing d3d8 directly makes the game crash at startup.

**Comment by AlpyneDreams** [comment]
CopyRects has been updated yet again. Let me know the issue persists.

**Comment by WinterSnowfall** [comment]
Well... the game now outright crashes once it gets to the main menu :sweat_smile: .

P.S.: There's nothing odd in the logs before the crash unfortunately.

**Comment by AlpyneDreams** [comment]
Weird...
I'll have to look more closely at this later

**Comment by AlpyneDreams** [comment]
Regression has been fixed. It's back to the original issue.

**Comment by AlpyneDreams** [comment]
Is the D3D8 version of this game available to buy anywhere? Just curious.

**Comment by WinterSnowfall** [comment]
Sadly, not really. Unless you thrift for new old stock retail copies (which is what I did, tbh).

**Comment by AlpyneDreams** [comment]
Issue should be fixed as of da01c36a56730c7ca827814ebd74ef39297a3e3c.
